# Generated by Django 3.2.15 on 2024-02-24 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=200, verbose_name='收件人')),
                ('subject', models.CharField(max_length=200, verbose_name='主题')),
                ('body', models.TextField(verbose_name='正文')),
                ('sent_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('sender', models.CharField(max_length=200, verbose_name='发件人')),
            ],
            options={
                'verbose_name': '邮件',
                'verbose_name_plural': '邮件',
            },
        ),
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='用户名')),
                ('time', models.CharField(default='', max_length=50, verbose_name='登陆时间')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='问题')),
                ('description', models.TextField(verbose_name='问题描述')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='用户名')),
                ('sname', models.CharField(default='', max_length=50, verbose_name='真实姓名')),
                ('password', models.CharField(default='', max_length=50, verbose_name='密码')),
                ('role', models.CharField(default='', max_length=50, verbose_name='角色')),
                ('bio', models.CharField(default='', max_length=500, null=True, verbose_name='个人介绍')),
                ('signature', models.CharField(default='', max_length=50, null=True, verbose_name='个性签名')),
                ('english_name', models.CharField(default='', max_length=50, null=True, verbose_name='英文名')),
                ('phone', models.CharField(default='', max_length=50, null=True, verbose_name='手机号码')),
                ('avatar', models.CharField(default='', max_length=200, null=True, verbose_name='头像url')),
                ('skills', models.CharField(default='', max_length=50, null=True, verbose_name='职业技能')),
                ('uid', models.CharField(default='', max_length=50, null=True, verbose_name='编号')),
                ('status', models.CharField(default='', max_length=50, null=True, verbose_name='状态')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='邮箱')),
                ('sex', models.CharField(default='', max_length=50, null=True, verbose_name='性别')),
                ('school', models.CharField(default='', max_length=50, null=True, verbose_name='地区')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='答案')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='myapp.question')),
            ],
        ),
    ]
