# Generated by Django 3.2.15 on 2024-02-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_purchaseinfo_stockinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('product_name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('quantity', models.IntegerField(verbose_name='销售数量')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='售价')),
                ('sale_time', models.DateTimeField(auto_now_add=True, verbose_name='销售时间')),
            ],
        ),
    ]
