# Generated by Django 3.2.15 on 2024-02-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_salesrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=21, max_digits=10, verbose_name='成本价'),
            preserve_default=False,
        ),
    ]
