# Generated by Django 3.2.15 on 2024-02-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_salesrecord_cost_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('item_name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('record_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
            ],
        ),
    ]
